# Generated by Django 4.0 on 2021-12-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_productgroup_group_alter_productgroup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='group',
            field=models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('machine', 'machine'), ('other', 'other')], default=('machine', 'machine'), max_length=7),
        ),
    ]
