# Generated by Django 4.0 on 2021-12-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_productgroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
