# Generated by Django 4.0 on 2021-12-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_productbrandmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.productgroup')),
            ],
        ),
    ]
