# Generated by Django 4.0 on 2021-12-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_productsubgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.productsubgroup')),
            ],
        ),
        migrations.RenameField(
            model_name='productbrandmodel',
            old_name='id_group',
            new_name='id_brand',
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.productcategory')),
            ],
        ),
    ]
