# Generated by Django 4.0 on 2021-12-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_productcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
