# Generated by Django 4.0 on 2021-12-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_technicalstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
